---
swagger: "2.0"
info:
  description: "Dipbit Pay Gateway API"
  version: "1.0.0"
  title: "Dipbit Pay Gateway API"
  contact:
    name: "API Support"
    url: "https://dipbitsupport.zendesk.com/hc/en-us"
    email: "support@mail.dipbit.com"
host: "paygw.dipbit.com"
basePath: "/"
schemes:
- "https"
paths:
  /v1/key/init:
    post:
      tags:
      - "User"
      summary: "init merchant ACCESS_KEY and ACCESS_TOKEN"
      description: "初始化accessKey"
      operationId: "init"
      produces:
      - "application/json"
      parameters:
      - name: "merchantID"
        in: "query"
        description: "商户ID\n"
        required: true
        type: "string"
      - name: "token"
        in: "query"
        description: "初始化token"
        required: true
        type: "string"
      responses:
        200:
          description: "Access Key信息"
          schema:
            $ref: "#/definitions/AccessTokenResponse"
        401:
          description: "ERROR Response"
          schema:
            $ref: "#/definitions/ErrorResponse"
  /api/v1/currencies:
    get:
      tags:
      - "Asset"
      summary: "获取所有支持的币种"
      description: "获取所有的支持币种"
      operationId: "getCurrencies"
      produces:
      - "application/json"
      parameters:
      - name: "merchantID"
        in: "query"
        description: "商户ID\n"
        required: true
        type: "string"
      responses:
        200:
          description: "Success"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Currency"
        401:
          description: "ERROR Response"
          schema:
            $ref: "#/definitions/ErrorResponse"
      security:
      - apiKeyId: []
      - apiSignature: []
  /api/v1/balance:
    get:
      tags:
      - "Asset"
      summary: "查询余额"
      description: "查询余额"
      operationId: "balance"
      produces:
      - "application/json"
      parameters:
      - name: "merchantID"
        in: "query"
        description: "商户ID\n"
        required: true
        type: "string"
      responses:
        200:
          description: "Success"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/BalanceResponse"
        401:
          description: "ERROR Response"
          schema:
            $ref: "#/definitions/ErrorResponse"
      security:
      - apiKeyId: []
      - apiSignature: []
  /api/v1/deposit/apply:
    post:
      tags:
      - "Deposit"
      summary: "申请充币"
      description: "申请充币"
      operationId: "depositApply"
      produces:
      - "application/json"
      parameters:
      - name: "merchantID"
        in: "query"
        description: "商户ID\n"
        required: true
        type: "string"
      - name: "merchantUserID"
        in: "query"
        description: "商户用户唯一标识\n"
        required: true
        type: "string"
      - name: "currency"
        in: "query"
        description: "数字货币代号，如ETH， BTC\n"
        required: true
        type: "string"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/DepositApplyResponse"
        401:
          description: "ERROR Response"
          schema:
            $ref: "#/definitions/ErrorResponse"
      security:
      - apiKeyId: []
      - apiSignature: []
  /api/v1/deposit/list:
    get:
      tags:
      - "Deposit"
      summary: "获取充币记录"
      description: "获取充币记录"
      operationId: "getDepositList"
      produces:
      - "application/json"
      parameters:
      - name: "merchantID"
        in: "query"
        description: "商户ID\n"
        required: true
        type: "string"
      - name: "merchantUserID"
        in: "query"
        description: "商户用户唯一标识\n"
        required: false
        type: "string"
      - name: "limit"
        in: "query"
        description: "Limit the result default 100"
        required: false
        type: "integer"
        default: 100
        maximum: 100
        minimum: 10
      - name: "offset"
        in: "query"
        description: "offset the result default 0"
        required: false
        type: "integer"
        default: 0
        minimum: 0
      responses:
        200:
          description: "Success"
          schema:
            type: "object"
            properties:
              items:
                type: "array"
                items:
                  $ref: "#/definitions/DepositListResponse"
              hasNext:
                type: "boolean"
        401:
          description: "ERROR Response"
          schema:
            $ref: "#/definitions/ErrorResponse"
      security:
      - apiKeyId: []
      - apiSignature: []
  /api/v1/withdraw/apply:
    post:
      tags:
      - "Withdraw"
      summary: "申请提币"
      description: "申请提币"
      operationId: "withdrawApply"
      produces:
      - "application/json"
      parameters:
      - name: "merchantID"
        in: "query"
        description: "商户ID\n"
        required: true
        type: "string"
      - name: "merchantUserID"
        in: "query"
        description: "商户用户唯一标识\n"
        required: true
        type: "string"
      - name: "currency"
        in: "query"
        description: "数字货币代号，如ETH， BTC\n"
        required: true
        type: "string"
      - name: "amount"
        in: "query"
        description: "数量\n"
        required: true
        type: "string"
      - name: "address"
        in: "query"
        description: "地址\n"
        required: true
        type: "string"
      - name: "clientOrderID"
        in: "query"
        description: "客户端请求唯一ID，用于订单唯一性"
        required: true
        type: "string"
      - name: "memo"
        in: "query"
        description: "部分数字货币充提币时需要的特殊备注"
        required: false
        type: "string"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/WithdrawApplyResponse"
        401:
          description: "ERROR Response"
          schema:
            $ref: "#/definitions/ErrorResponse"
      security:
      - apiKeyId: []
      - apiSignature: []
  /api/v1/withdraw/list:
    get:
      tags:
      - "Withdraw"
      summary: "提币记录查询"
      description: "提币记录查询"
      operationId: "withdrawList"
      produces:
      - "application/json"
      parameters:
      - name: "clientOrderID"
        in: "query"
        description: "客户端请求唯一ID，用于订单唯一性"
        required: false
        type: "string"
      - name: "merchantID"
        in: "query"
        description: "商户ID\n"
        required: true
        type: "string"
      - name: "limit"
        in: "query"
        description: "Limit the result default 100"
        required: false
        type: "integer"
        default: 100
        maximum: 100
        minimum: 10
      - name: "offset"
        in: "query"
        description: "offset the result default 0"
        required: false
        type: "integer"
        default: 0
        minimum: 0
      responses:
        200:
          description: "Success"
          schema:
            type: "object"
            properties:
              items:
                type: "array"
                items:
                  $ref: "#/definitions/WithdrawListResponse"
              hasNext:
                type: "boolean"
        401:
          description: "ERROR Response"
          schema:
            $ref: "#/definitions/ErrorResponse"
      security:
      - apiKeyId: []
      - apiSignature: []
securityDefinitions:
  apiKeyId:
    type: "apiKey"
    name: "X-AccessKeyId"
    in: "header"
  apiSignature:
    type: "apiKey"
    name: "signature"
    in: "header"
definitions:
  AccessTokenResponse:
    type: "object"
    properties:
      accessKey:
        type: "string"
      accessSecret:
        type: "string"
    description: "初始化AccessKey返回对象"
    example:
      accessKey: "accessKey"
      accessSecret: "accessSecret"
  DepositApplyResponse:
    type: "object"
    properties:
      address:
        type: "string"
      currency:
        type: "string"
      memo:
        type: "string"
    description: "充币申请返回对象"
    example:
      address: "address"
      memo: "memo"
      currency: "currency"
  WithdrawApplyResponse:
    type: "object"
    properties:
      transactionNum:
        type: "string"
      clientOrderID:
        type: "string"
    description: "提币申请返回对象"
    example:
      transactionNum: "transactionNum"
      clientOrderID: "clientOrderID"
  DepositListResponse:
    type: "object"
    properties:
      time:
        type: "string"
      amount:
        type: "number"
      currency:
        type: "string"
        description: "币种"
      merchangtUserID:
        type: "string"
        description: "商户用户唯一标识"
      transactionNum:
        type: "string"
        description: "Dipbit系统交易ID"
      txID:
        type: "string"
        description: "链上transactionID"
      status:
        type: "string"
        enum:
        - "PROCESSING"
        - "SUCCESS"
        - "FAIL"
    description: "充币查询列表结果"
    example:
      amount: 0.80082819046101150206595775671303272247314453125
      transactionNum: "transactionNum"
      merchangtUserID: "merchangtUserID"
      txID: "txID"
      currency: "currency"
      time: "time"
      status: "PROCESSING"
  WithdrawListResponse:
    type: "object"
    properties:
      time:
        type: "string"
      amount:
        type: "number"
      currency:
        type: "string"
        description: "币种"
      transactionNum:
        type: "string"
        description: "Dipbit系统交易ID"
      clientOrderID:
        type: "string"
        description: "客户方系统请求唯一ID"
      txID:
        type: "string"
        description: "链上transactionID"
      status:
        type: "string"
        enum:
        - "PROCESSING"
        - "SUCCESS"
        - "FAIL"
    description: "提币查询列表结果"
    example:
      amount: 0.80082819046101150206595775671303272247314453125
      transactionNum: "transactionNum"
      clientOrderID: "clientOrderID"
      txID: "txID"
      currency: "currency"
      time: "time"
      status: "PROCESSING"
  BalanceResponse:
    type: "object"
    properties:
      currency:
        type: "string"
      available:
        type: "number"
      freeze:
        type: "number"
    example:
      freeze: 6.02745618307040320615897144307382404804229736328125
      available: 0.80082819046101150206595775671303272247314453125
      currency: "currency"
  ErrorResponse:
    type: "object"
    properties:
      msg:
        type: "string"
      code:
        type: "string"
  Currency:
    type: "object"
    properties:
      currency:
        type: "string"
        description: "数字货币代号"
      precision:
        type: "number"
        description: "数字货币精度"
      miniWithdrawAmount:
        type: "number"
        description: "最小提币额度"
    description: "货币"
    example:
      miniWithdrawAmount: 6.02745618307040320615897144307382404804229736328125
      precision: 0.80082819046101150206595775671303272247314453125
      currency: "currency"
  inline_response_200:
    properties:
      items:
        type: "array"
        items:
          $ref: "#/definitions/DepositListResponse"
      hasNext:
        type: "boolean"
    example:
      hasNext: true
      items:
      - amount: 0.80082819046101150206595775671303272247314453125
        transactionNum: "transactionNum"
        merchangtUserID: "merchangtUserID"
        txID: "txID"
        currency: "currency"
        time: "time"
        status: "PROCESSING"
      - amount: 0.80082819046101150206595775671303272247314453125
        transactionNum: "transactionNum"
        merchangtUserID: "merchangtUserID"
        txID: "txID"
        currency: "currency"
        time: "time"
        status: "PROCESSING"
  inline_response_200_1:
    properties:
      items:
        type: "array"
        items:
          $ref: "#/definitions/WithdrawListResponse"
      hasNext:
        type: "boolean"
    example:
      hasNext: true
      items:
      - amount: 0.80082819046101150206595775671303272247314453125
        transactionNum: "transactionNum"
        clientOrderID: "clientOrderID"
        txID: "txID"
        currency: "currency"
        time: "time"
        status: "PROCESSING"
      - amount: 0.80082819046101150206595775671303272247314453125
        transactionNum: "transactionNum"
        clientOrderID: "clientOrderID"
        txID: "txID"
        currency: "currency"
        time: "time"
        status: "PROCESSING"
parameters:
  Token:
    name: "token"
    in: "query"
    description: "初始化token"
    required: true
    type: "string"
  MerchantID:
    name: "merchantID"
    in: "query"
    description: "商户ID\n"
    required: true
    type: "string"
  MerchantUserID:
    name: "merchantUserID"
    in: "query"
    description: "商户用户唯一标识\n"
    required: true
    type: "string"
  MerchantUserIDOptional:
    name: "merchantUserID"
    in: "query"
    description: "商户用户唯一标识\n"
    required: false
    type: "string"
  Currency:
    name: "currency"
    in: "query"
    description: "数字货币代号，如ETH， BTC\n"
    required: true
    type: "string"
  Amount:
    name: "amount"
    in: "query"
    description: "数量\n"
    required: true
    type: "string"
  Address:
    name: "address"
    in: "query"
    description: "地址\n"
    required: true
    type: "string"
  Memo:
    name: "memo"
    in: "query"
    description: "部分数字货币充提币时需要的特殊备注"
    required: false
    type: "string"
  ClientOrderID:
    name: "clientOrderID"
    in: "query"
    description: "客户端请求唯一ID，用于订单唯一性"
    required: true
    type: "string"
  ClientOrderIDOptional:
    name: "clientOrderID"
    in: "query"
    description: "客户端请求唯一ID，用于订单唯一性"
    required: false
    type: "string"
  Limit:
    name: "limit"
    in: "query"
    description: "Limit the result default 100"
    required: false
    type: "integer"
    default: 100
    maximum: 100
    minimum: 10
  Offset:
    name: "offset"
    in: "query"
    description: "offset the result default 0"
    required: false
    type: "integer"
    default: 0
    minimum: 0
